### ISSUE TITLE
Can't authenticate other users on Debian GNU/Linux 8 (jessie)

### ISSUE THREAD

**Issue by tasaif** [FirefighterBlu3/python-pam#10]
Sample works when run as root
Sample does not work when running as user A authenticating credentials for user B

**Comment by FirefighterBlu3** [comment]
@tasaif if it works as root but not as a user, this is a PAM setup/configuration problem. this module doesn't infer (nor should it) any privilege level when working. it simply wraps the C library for PAM in the authentication process and exposes it in a pythonic fashion

**Comment by MasterOdin** [comment]
We found that on default Ubuntu/Debian installation, the user we wanted to utilize python-pam with needed to be added to the shadow group.

**Comment by tasaif** [comment]
Thanks MastOdin
