### ISSUE TITLE
Python PAM root authentication

### ISSUE THREAD

**Issue by cioby23** [FirefighterBlu3/python-pam#13]
Hello,
I tried to use this library and test PAM authentication using the root account on two different Linux distros but every time it fails with the error:

**python /usr/lib/python3.7/site-packages/pam.py
Username: root
Password: 
3 Error in service module**

I'm using Python 3.7. Also in the logs a see the following error:
**python: pam_securetty(login:auth): cannot determine user's tty**

Is python 3.7 supported or this is an PAM issue ? I tested with normal accounts and it works fine

**Comment by xiongyihui** [comment]
It seems the user `root` is not supported. Other users are OK.

**Comment by FirefighterBlu3** [comment]
this is two-fold. i've added code to set the PAM_TTY item for `pam_securetty`, but it will continue to fail if you have a `pam_unix` method of verifying the calling user (`unix_chkpwd` helper) and `pam.py` is run as non-root. unix_chkpwd does not setuid(0) and so regardless of whether or not the calling user is in /etc/shadow, it will fail to authenticate you purely because it cannot open and read it.

if pam.py is run as root, authentication as root will succeed.

**Comment by JedMeister** [comment]
> if pam.py is run as root, authentication as root will succeed.

Hmm, it's still not working here, even when running as root (on Debian Buster)...!?

However, after a ton of digging around, it appears that the issue is with the PAM `login` service (default in `pam.py`) not working with `root` user for some reason!
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
>>> p = pam.pam()
>>> p.authenticate('root', 'right_password')
False
>>> p.reason
'Error in service module'
>>> p.authenticate('root', 'wrong_password')
False
>>> p.reason
'Error in service module'
```

However, a workaround is to use the `passwd` service instead:
```
>>> p.authenticate('root', 'right_password', service='passwd') 
True
>>> p.authenticate('root', 'wrong_password', service='passwd')
False
>>> p.reason
'Authentication failure'
```

**Comment by JedMeister** [comment]
FYI, here's a workaround. It's perhaps a bit hacky, but it allows the root user to authenticate using the (nearly) normal pam 'login' service whilst still checking that the `tty` is noted in `/etc/securetty`:
```
# cat root_auth.py 
#!/usr/bin/python3

import subprocess
import pam
from pathlib import Path

# create temp 'login' service with securetty checking disabled
login = Path('/etc/pam.d/login')
login_tmp = Path('/etc/pam.d/login.tmp')
with login.open('r') as fob1, login_tmp.open('w') as fob2:
    for line in fob1:
        if 'pam_securetty.so' in line:
            line = f'#{line}'
        fob2.write(line)

# manually check tty
tty = subprocess.run(['tty'], capture_output=True, text=True).stdout
if tty.startswith('/dev/'):
    tty=tty[5:]

# before authenticating root, check that it is using "securetty"
p = pam.pam()
with open('/etc/securetty', 'r') as fob:
    if tty in fob:
        # authenticate using the temp 'login' service we created
        auth = p.authenticate('root', 'right_password', service=login_tmp.name)

# remove temp 'login' service
login_tmp.unlink()

print(f'auth: {auth}\nreason: {p.reason}')
```
Output:
```
auth: True
reason: Success
```

**Comment by greenseeker** [comment]
It would be really helpful to find a proper solution to this issue.

**Comment by JedMeister** [comment]
@greenseeker 
> It would be really helpful to find a proper solution to this issue.

As I noted above:

> it's a feature, rather than a bug. As it turns out, if the stdin of the `tty` command is wrapped, then it can't determine it's tty. Hence it is not able to compare tty against securetty, so authentication fails.

So the PAM `login` service is working exactly as intended! I.e. denying any wrapped attempt to authenticate.

One way to work around that is the (somewhat hacky) approach I took in [my wrapper for this module](https://github.com/FirefighterBlu3/python-pam/issues/13#issuecomment-775569914). To maintain security, that does it's own securetty check and temporarily disables the system securetty check when authenticating root against the default `login` PAM service.

If you don't want to use my code/wrapper, then you'll need to use the `passwd` (or some other) PAM authentication service (i.e. `service='passwd'`). On the downside, using `passwd` is not as secure as using `login`.

**Comment by greenseeker** [comment]
@JedMeister:
> it's a feature, rather than a bug. As it turns out, if the stdin of the `tty` command is wrapped, then it can't determine it's tty. 
> ...
> So the PAM `login` service is working exactly as intended! I.e. denying any wrapped attempt to authenticate.

Maybe I just don't understand what you mean by 'wrapped' here.
