### ISSUE TITLE
cdll unable to find dlls

### ISSUE THREAD

**Issue by codesiddhar** [FirefighterBlu3/python-pam#15]
ctypes cdll unable to find c lib and pam lib, in my os windows 7 64bit. I m ok to tweak the cdll with absolute path or hardcoded path of DLL. but I donno where to download those dlls?

**Comment by FirefighterBlu3** [comment]
I've left this open for anyone to post research and comment -- I don't know if this is even a thing for Windows. PAM is a system for authenticating on *nix type platforms and I've never encountered anyone implementing it for a Windows system.

I'm going to close this for now, if anyone wants to post about such an implementation, feel free to reopen.
