### ISSUE TITLE
Unable to authenticate users other than currently logged in user

### ISSUE THREAD

**Issue by gkmcd** [FirefighterBlu3/python-pam#28]
Attempting to authenticate any user other than the (non-root) user running the script fails.

```
Python 3.9.7 (default, Oct 10 2021, 15:13:22) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
>>> pam_session = pam.internals.PamAuthenticator()
>>> pam_session.authenticate('some_other_user', 'password', service='system-auth')
as1: 6
as2: 6
as3: 6
6
>>> pam_session.authenticate('current_user', 'password', service='system-auth')
as1: 0
as2: 0
as3: 0
0
```
This is consistent regardless of the PAM service used. Specifying any of the following PAM services defined in /etc/pam.d/ produces the same behavior:

```
user@machine ~> cat /etc/pam.d/system-auth
#%PAM-1.0

auth       required                    pam_faillock.so      preauth
# Optionally use requisite above if you do not want to prompt for the password
# on locked accounts.
auth       [success=2 default=ignore]  pam_unix.so          try_first_pass nullok
-auth      [success=1 default=ignore]  pam_systemd_home.so
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
auth       required                    pam_env.so
auth       required                    pam_faillock.so      authsucc
# If you drop the above call to pam_faillock.so the lock will be done also
# on non-consecutive authentication failures.

-account   [success=1 default=ignore]  pam_systemd_home.so
account    required                    pam_unix.so
account    optional                    pam_permit.so
account    required                    pam_time.so

-password  [success=1 default=ignore]  pam_systemd_home.so
password   required                    pam_unix.so          try_first_pass nullok shadow sha512
password   optional                    pam_permit.so

session    required                    pam_limits.so
session    required                    pam_unix.so
session    optional                    pam_permit.so
```
```
user@machine ~> cat /etc/pam.d/login 
#%PAM-1.0

auth       required     pam_securetty.so
auth       requisite    pam_nologin.so
auth       include      system-local-login
account    include      system-local-login
session    include      system-local-login
password   include      system-local-login
```

```
user@machine ~> cat /etc/pam.d/custom-simple
#%PAM-1.0
auth    required    pam_unix.so nullok
account required    pam_unix.so
session required    pam_unix.so
```

The example code above succeeds to authorise any user when run as root. Is it a requirement of this library/PAM to be executed as root, or is my usage and/or PAM configuration bad?

**Comment by gkmcd** [comment]
Issue #10 suggests adding the user to the shadow group, however this appears to be bad security advice. I don't think it is a good idea to give a web application access to shadow files?

See:
https://tldp.org/HOWTO/Shadow-Password-HOWTO-5.html#ss5.5

> None of the users on the system should actually be in the shadow group.

and
https://serverfault.com/a/1076189
https://serverfault.com/a/133235

**Comment by FirefighterBlu3** [comment]
I suspect something may need to be adjusted in your pam config. I've tested with wholly unprivileged users and authenticated my own account successfully. (I updated the `__init__.py` to provide `authenticate()` directly but this doesn't change the code functionality)

```python
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
>>> pam.authenticate('david', 'xxxxxxxx', service='system-auth')
0
>>> pam.authenticate('david', 'badpassword', service='system-auth')
7
>>> pam.authenticate('david', 'badpassword', service='system-auth', print_failure_messages=True)
Failure: Authentication failure
7
```

Error code 6 is a PAM_PERM_DENIED failure.

**Comment by FirefighterBlu3** [comment]
If I modify my `system-auth` to match yours, I also get the same type of error. I have a networked authentication system here so my setup is a little different. I have `pam_sss` in play. My username/pass doesn't exist in local files.

**Comment by FirefighterBlu3** [comment]
Is this an Arch system?

**Comment by gkmcd** [comment]
@FirefighterBlu3 thanks for your response. Yes, my systems all run arch.

**Comment by FirefighterBlu3** [comment]
@gkmcd do you have /usr/bin/unix_chkpwd and is it suid?

**Comment by FirefighterBlu3** [comment]
@gkmcd please try these commands, replace `good` with your account's password and `david` with your username. the user running the authentication can only verify their own password. if you use root, you can verify any account.

```
~$ mkfifo /tmp/myfifo

~$ (echo -ne 'good\0' > /tmp/myfifo & /usr/bin/unix_chkpwd david nullok < /tmp/myfifo ) ; echo $?
0

~$ (echo -ne 'bad\0' > /tmp/myfifo & /usr/bin/unix_chkpwd david nullok < /tmp/myfifo ) ; echo $?
7

~$ (echo -ne 'good\0' > /tmp/myfifo & /usr/bin/unix_chkpwd someotheruser nullok < /tmp/myfifo ) ; echo $?
9
```

`pam_unix.so` and `unix_chkpwd` are intentionally written to operate in 1 of two modes
* your tool runs as *root*, you can verify any password
* your tool runs as *non-root*, you can only verify the password of the user running as

This means that if you need to authenticate users other than yourself using python-pam (or any tool that uses pam_unix.so), you have to obtain root. Your options at this point are to add an authentication layer to your stack which at some point has root. `sssd` (`pam_sss.so`) is a common setup. It's pretty easy to implement and is extensible. I use it for my networked auth (ldap) on numerous systems (which are all also Arch).

**Comment by gkmcd** [comment]
> @gkmcd do you have `/usr/bin/unix_chkpwd` and is it suid?

Yes and Yes

```
user@machine ~> ls -al /usr/bin/unix_chkpwd 
-rwsr-sr-x 1 root root 38744 Sep  8 21:18 /usr/bin/unix_chkpwd
user@machine ~> find /usr/bin/unix_chkpwd -perm /4000 -ls
    12890     40 -rwsr-sr-x   1 root     root        38744 Sep  8 21:18 /usr/bin/unix_chkpwd
user@machine ~> find /usr/bin/unix_chkpwd -perm /2000 -ls
    12890     40 -rwsr-sr-x   1 root     root        38744 Sep  8 21:18 /usr/bin/unix_chkpwd
```

**Comment by gkmcd** [comment]
> @gkmcd please try these commands, replace `good` with your account's password and `david` with your username. the user running the authentication can only verify their own password. if you use root, you can verify any account.
> 
> ```
> ~$ mkfifo /tmp/myfifo
> 
> ~$ (echo -ne 'good\0' > /tmp/myfifo & /usr/bin/unix_chkpwd david nullok < /tmp/myfifo ) ; echo $?
> 0
> 
> ~$ (echo -ne 'bad\0' > /tmp/myfifo & /usr/bin/unix_chkpwd david nullok < /tmp/myfifo ) ; echo $?
> 7
> 
> ~$ (echo -ne 'good\0' > /tmp/myfifo & /usr/bin/unix_chkpwd someotheruser nullok < /tmp/myfifo ) ; echo $?
> 9
> ```
 
Output is identical to your example, i.e 0, 7, 9.

> `pam_unix.so` and `unix_chkpwd` are intentionally written to operate in 1 of two modes
> 
>     * your tool runs as _root_, you can verify any password
> 
>     * your tool runs as _non-root_, you can only verify the password of the user running as
> 
> 
> This means that if you need to authenticate users other than yourself using python-pam (or any tool that uses pam_unix.so), you have to obtain root. Your options at this point are to add an authentication layer to your stack which at some point has root. `sssd` (`pam_sss.so`) is a common setup. It's pretty easy to implement and is extensible. I use it for my networked auth (ldap) on numerous systems (which are all also Arch).

OK, that makes sense. FYI, my use case is a shim script called by Rclone to authorise a given user and return a dynamically generated backend to Rclone (see: https://rclone.org/commands/rclone_serve_webdav/#auth-proxy).

I will try to get my head around pam_sss.so. Thank you for your help!
