### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by LeTink** [FirefighterBlu3/python-pam#30]
Hi, 

Just after some clarity:  in your examples you're logged in as 'david' and check david's password using your module. 

What would I need to do to allow for checking someone else's password? 

Just in the same way I can `su - otheruser` from the command line as myself I'd like to be able to check if a password for `otheruser` passed to the python script is valid.

**Comment by FirefighterBlu3** [comment]
You can check someone else's password in the script IF your backend proxies with root level permissions. If your system doesn't do this (such as if you're using simple standard unix password files and no daemon or suid tooling) then as a user you can _only_ check your own password.

The reason why is that this is a script and under Linux, scripts cannot be suid, regardless of the language. the `su` tool is a compiled executable so it can be suid root.

That said, you can build an executable out of python and a script implementing this module and that executable can then be suid root. OR, you can make a tiny wrapper that (authenticates of course!) is suid root then calls this script.

**Comment by FirefighterBlu3** [comment]
closing
