### ISSUE TITLE
Documentation does not match API

### ISSUE THREAD

**Issue by axonxorz** [FirefighterBlu3/python-pam#31]
Hello there, with the new 2.0.0 release, the API documentation does not appear to match the module's new API.

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
>>> p = pam.authenticate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/virtualenvs/system-config/lib/python3.9/site-packages/pam/__init__.py", line 125, in authenticate
    return __PA.authenticate(*args, **kvargs)
TypeError: authenticate() missing 2 required positional arguments: 'username' and 'password'
``` 

This can be overcome by calling as such:

`result = pam.authenticate(username='foo', password='bar')`

However, `pam.authenticate` no longer returns a boolean, it returns the internal PAM_* constants

**Comment by FirefighterBlu3** [comment]
@axonxorz give this a try please

**Comment by axonxorz** [comment]
@FirefighterBlu3 are there any requirements to get this to build? I ran into what appears to be a [distutils problem](https://gist.github.com/axonxorz/e8a63079debe1765d709f917d1f56b51) running `pip install -e ./[path_to_pam]

Ubuntu 21.10 Server
Python 3.9.7

**Comment by FirefighterBlu3** [comment]
you can run `make build` and it'll produce a package file for you in ./dist

**Comment by Torxed** [comment]
```python
>>> import pam
>>> pam
<module 'pam' from '/home/anton/github/python-pam/src/pam/__init__.py'>
>>> pam.authenticate('test', 'test')
False
>>> pam.authenticate('anton', 'test')
True
```
```bash
[anton python-pam]$ git status
HEAD detached at de17aa2
```

Works. Ended up here after release notes not mentioning that `pam.pam()` has been deprecated and now requires user and password as well.
```
>>> import pam
>>> pam.pam()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pam/__init__.py", line 125, in authenticate
    return __PA.authenticate(*args, **kvargs)
TypeError: authenticate() missing 2 required positional arguments: 'username' and 'password'
```
