### ISSUE TITLE
AttributeError: Symbol not found: pam_end

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [FirefighterBlu3/python-pam#6]
Thank you for the module!

I have an issue when importing the module. I've made the following steps:
1. `pip install python-pam` (in virtuelenv with Python 3.5 on Alpine Linux)
2. `python` to open an interactive python CLI
3. `import pam` <-- This results in the following AttributeError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.5/site-packages/pam.py", line 77, in <module>
    pam_end                   = libpam.pam_end
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: Symbol not found: pam_end
```

I think this error occurres because of an incompatible pam-system-library. I checked my `libpam.so*`-files for a symbol named `pam_end` and I found it. I'm asking why can't the module load the symbol?

I've put my `libpam.so*`-files in a zip-archive for testing to reproduce this error:

[libpam.so.zip](https://github.com/FirefighterBlu3/python-pam/files/546191/libpam.so.zip)

Is this an error of my platform which provides these `libpam.so*`-files or is there a bug in the module? The `pam_end` symbol seems to be the first symbol loaded from the library. Maybe the whole library fails to load?

I've patched the `pam.py` of the module and added the following code near to line 72:

``` python
print(libpam)
```

Output:

```
<CDLL 'None', handle 7f4fcbb12a20 at 0x7f4fcb9b9828>
```

Hope that helps. I can provide more informations if needed.

**Comment by FirefighterBlu3** [comment]
@NIPE-SYSTEMS does this still affect you?

**Comment by NIPE-SYSTEMS** [comment]
@FirefighterBlu3 No, since I'm not using Alpine anymore in none of my environments. This issue was "a long time ago"... In that time I needed PAM access in Python somehow. Either I found another way of accessing the PAM or I canceled the project, I cannot remember... :wink: I'm okay with closing this issue.

**Comment by traverseda** [comment]
It affects me! Might have something to do with alpine being musl based?

**Comment by traverseda** [comment]
So 1.8.4 throws the error at import, which is what would be better. 2.0.2 throws it at run time instead. It looks like this package is in alpine-testing, although I can confirm it's not working there either.

Trying to build from source didn't do the trick either (using `pip install --no-binary=python-pam`. This is definitely an alpine linux problem, not a python-pam problem, but it would still be good to get it working.

**Comment by traverseda** [comment]
Moved my project to the default docker python, which is a shame since it's meant to be run on an embedded system and the image is an order of magnitude larger now.

Let me know if you want any help testing or reproducing this. Python-pam pairs well with alpine for making very minimal services that authenticate against local users. Things like router config panels, crontab editors, etc.
