### ISSUE TITLE
Please add LICENSE to the PyPI manifest

### ISSUE THREAD

**Issue by eli-schwartz** [FirefighterBlu3/python-pam#9]
Downstream distributors using the PyPI sources might need the license file, but by default it is not included in sdist releases.

This matters to Arch Linux at least, since the MIT license is not considered a ["common" license](https://wiki.archlinux.org/index.php/PKGBUILD#license) as it contains a unique copyright line, and must therefore be packaged separately.

**Comment by FirefighterBlu3** [comment]
LICENSE file specifically for sdist added via MANIFEST.in
